version: '3.8'

services:
  backend:
    build:
      context: ./fastapi_backend
    ports:
      - "8000:8000"
    env_file:
      - ./fastapi_backend/.env
    volumes:
      - ./fastapi_backend:/app
    depends_on:
      - db

  frontend:
    build:
      context: ./vue_interface
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: filecloud
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: